// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcuqdauufcvttvqobqgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdXFkYXV1ZmN2dHR2cW9icWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjU2NDEsImV4cCI6MjA3MTk0MTY0MX0.1moU3Yoc1e6SyXPEN7BQM55_jPtIu2OxR1vmlMrk7OA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});